spring:
  application:
    name: rent
  thymeleaf:
    cache: false

# DB Configuration
datasource:
  url: jdbc:h2:file:~/rent.db;
  driver-class-name: org.h2.Driver
  username: admin
  password: admin

# JPA Configuration
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  open-in-view: false

# H2 Configuration
h2:
  console:
    enabled: true

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: myapp
  port: 8443